name: HARD RESET TEST

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "🔥 GITHUB IS WORKING PROPERLY"

      - name: Show Python version
        run: python --version
