name: TEST BOT

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "STEP 1 WORKING"

      - name: Step 2
        run: echo "STEP 2 WORKING"

      - name: Step 3
        run: python --version
